SET(P_C_BINDING_SRCS
  
  
  c_binding/cb_ar/par_all_structs.c
  c_binding/cb_ar/par_struct_nets.c
  c_binding/cb_ar/par_structs.c
  c_binding/cb_ar/pclose_ar_file.c
  c_binding/cb_ar/pdel_all_structs.c
  c_binding/cb_ar/pdel_all_structs_ar.c
  c_binding/cb_ar/pdel_struct.c
  c_binding/cb_ar/pdel_struct_net.c
  c_binding/cb_ar/pdel_struct_nets_ar.c
  c_binding/cb_ar/pdel_structs_ar.c
  c_binding/cb_ar/phg_cb_resize_store.c
  c_binding/cb_ar/pinq_all_conf_structs.c
  c_binding/cb_ar/pinq_ar_files.c
  c_binding/cb_ar/pinq_ar_st.c
  c_binding/cb_ar/pinq_conf_res.c
  c_binding/cb_ar/pinq_conf_structs_net.c
  c_binding/cb_ar/popen_ar_file.c
  c_binding/cb_ar/pret_all_structs.c
  c_binding/cb_ar/pret_struct_ids.c
  c_binding/cb_ar/pret_struct_nets.c
  c_binding/cb_ar/pret_structs.c
  c_binding/cb_ar/pset_conf_res.c
  c_binding/cb_conf/pxinq_conf_hcsf.c
  c_binding/cb_conf/pxset_conf_file_name.c
  c_binding/cb_conf/pxset_conf_hcsf.c
  c_binding/cb_el/padd_names_set.c
  c_binding/cb_el/pexec_struct.c
  c_binding/cb_el/pfill_area.c
  c_binding/cb_el/pfill_area3.c
  c_binding/cb_el/pfill_area_set.c
  c_binding/cb_el/pfill_area_set3.c
  c_binding/cb_el/plabel.c
  c_binding/cb_el/ppolyline.c
  c_binding/cb_el/ppolyline3.c
  c_binding/cb_el/ppolymarker.c
  c_binding/cb_el/ppolymarker3.c
  c_binding/cb_el/premove_names_set.c
  c_binding/cb_el/pset_anno_char_up_vec.c
  c_binding/cb_el/pset_back_int_colr.c
  c_binding/cb_el/pset_back_int_colr_ind.c
  c_binding/cb_el/pset_char_expan.c
  c_binding/cb_el/pset_char_ht.c
  c_binding/cb_el/pset_char_space.c
  c_binding/cb_el/pset_char_up_vec.c
  c_binding/cb_el/pset_edge_colr.c
  c_binding/cb_el/pset_edge_colr_ind.c
  c_binding/cb_el/pset_edge_flag.c
  c_binding/cb_el/pset_edge_ind.c
  c_binding/cb_el/pset_edgetype.c
  c_binding/cb_el/pset_edgewidth.c
  c_binding/cb_el/pset_global_tran3.c
  c_binding/cb_el/pset_hlhsr_id.c
  c_binding/cb_el/pset_indiv_asf.c
  c_binding/cb_el/pset_int_colr.c
  c_binding/cb_el/pset_int_colr_ind.c
  c_binding/cb_el/pset_int_ind.c
  c_binding/cb_el/pset_int_style.c
  c_binding/cb_el/pset_int_style_ind.c
  c_binding/cb_el/pset_line_colr.c
  c_binding/cb_el/pset_line_colr_ind.c
  c_binding/cb_el/pset_line_ind.c
  c_binding/cb_el/pset_linetype.c
  c_binding/cb_el/pset_linewidth.c
  c_binding/cb_el/pset_local_tran3.c
  c_binding/cb_el/pset_marker_colr.c
  c_binding/cb_el/pset_marker_colr_ind.c
  c_binding/cb_el/pset_marker_ind.c
  c_binding/cb_el/pset_marker_size.c
  c_binding/cb_el/pset_marker_type.c
  c_binding/cb_el/pset_pick_id.c
  c_binding/cb_el/pset_view_ind.c
  c_binding/cb_extel/pfill_area_set3_data.c
  c_binding/cb_extel/pfill_area_set_data.c
  c_binding/cb_extel/pset_alpha_channel.c
  c_binding/cb_extel/pset_back_int_shad_meth.c
  c_binding/cb_extel/pset_back_int_style.c
  c_binding/cb_extel/pset_back_int_style_ind.c
  c_binding/cb_extel/pset_back_refl_eqn.c
  c_binding/cb_extel/pset_back_refl_props.c
  c_binding/cb_extel/pset_face_cull_mode.c
  c_binding/cb_extel/pset_face_disting_mode.c
  c_binding/cb_extel/pset_int_shad_meth.c
  c_binding/cb_extel/pset_light_src_state.c
  c_binding/cb_extel/pset_model_clip_ind.c
  c_binding/cb_extel/pset_model_clip_vol3.c
  c_binding/cb_extel/pset_of_fill_area_set3_data.c
  c_binding/cb_extel/pset_refl_eqn.c
  c_binding/cb_extel/pset_refl_model.c
  c_binding/cb_extel/pset_refl_props.c
  c_binding/cb_extel/pset_text_colr.c
  c_binding/cb_globals.c
  c_binding/cb_inp/pawait_event.c
  c_binding/cb_inp/pflush_events.c
  c_binding/cb_inp/pget_choice.c
  c_binding/cb_inp/pget_loc.c
  c_binding/cb_inp/pget_loc3.c
  c_binding/cb_inp/pget_pick.c
  c_binding/cb_inp/pget_stroke.c
  c_binding/cb_inp/pget_stroke3.c
  c_binding/cb_inp/pget_val.c
  c_binding/cb_inp/pinit_choice3.c
  c_binding/cb_inp/pinit_loc3.c
  c_binding/cb_inp/pinit_pick3.c
  c_binding/cb_inp/pinit_string.c
  c_binding/cb_inp/pinit_string3.c
  c_binding/cb_inp/pinit_stroke3.c
  c_binding/cb_inp/pinit_val3.c
  c_binding/cb_inp/preq_choice.c
  c_binding/cb_inp/preq_loc3.c
  c_binding/cb_inp/preq_pick.c
  c_binding/cb_inp/preq_string.c
  c_binding/cb_inp/preq_stroke3.c
  c_binding/cb_inp/preq_valuator.c
  c_binding/cb_inp/psample_loc.c
  c_binding/cb_inp/psample_loc3.c
  c_binding/cb_inp/psample_pick.c
  c_binding/cb_inp/psample_string.c
  c_binding/cb_inp/psample_stroke.c
  c_binding/cb_inp/psample_stroke3.c
  c_binding/cb_inp/pset_choice_mode.c
  c_binding/cb_inp/pset_highl_filter.c
  c_binding/cb_inp/pset_loc_mode.c
  c_binding/cb_inp/pset_pick_filter.c
  c_binding/cb_inp/pset_pick_mode.c
  c_binding/cb_inp/pset_string_mode.c
  c_binding/cb_inp/pset_stroke_mode.c
  c_binding/cb_inp/pset_val_mode.c
  c_binding/cb_lite/pinq_light_src_rep.c
  c_binding/cb_phg/pclose_phigs.c
  c_binding/cb_phg/pcreate_store.c
  c_binding/cb_phg/pdel_store.c
  c_binding/cb_phg/phg_cb_destroy_all_stores.c
  c_binding/cb_phg/popen_phigs.c
  c_binding/cb_str/pchange_struct_id.c
  c_binding/cb_str/pchange_struct_id_refs.c
  c_binding/cb_str/pchange_struct_refs.c
  c_binding/cb_str/pclose_struct.c
  c_binding/cb_str/pcopy_all_elems_struct.c
  c_binding/cb_str/pdel_elem.c
  c_binding/cb_str/pdel_elem_range.c
  c_binding/cb_str/pdel_elems_labels.c
  c_binding/cb_str/pelem_search.c
  c_binding/cb_str/pempty_struct.c
  c_binding/cb_str/phg_cb_store_el_data.c
  c_binding/cb_str/phg_cb_store_el_size.c
  c_binding/cb_str/pinq_cur_elem_content.c
  c_binding/cb_str/pinq_cur_elem_type_size.c
  c_binding/cb_str/pinq_edit_mode.c
  c_binding/cb_str/pinq_elem_content.c
  c_binding/cb_str/pinq_elem_ptr.c
  c_binding/cb_str/pinq_elem_type_size.c
  c_binding/cb_str/pinq_open_struct.c
  c_binding/cb_str/pinq_struct_st.c
  c_binding/cb_str/pinq_struct_status.c
  c_binding/cb_str/poffset_elem_ptr.c
  c_binding/cb_str/popen_struct.c
  c_binding/cb_str/pset_edit_mode.c
  c_binding/cb_str/pset_elem_ptr.c
  c_binding/cb_str/pset_elem_ptr_label.c
  c_binding/cb_text/panno_text_rel.c
  c_binding/cb_text/panno_text_rel3.c
  c_binding/cb_text/pset_anno_char_ht.c
  c_binding/cb_text/pset_anno_path.c
  c_binding/cb_text/pset_text_align.c
  c_binding/cb_text/pset_text_colr_ind.c
  c_binding/cb_text/pset_text_font.c
  c_binding/cb_text/pset_text_ind.c
  c_binding/cb_text/pset_text_path.c
  c_binding/cb_text/pset_text_prec.c
  c_binding/cb_text/ptext.c
  c_binding/cb_text/ptext3.c
  c_binding/cb_tr/pbuild_tran_matrix3.c
  c_binding/cb_tr/pcompose_matrix.c
  c_binding/cb_tr/pcompose_matrix3.c
  c_binding/cb_tr/pcompose_tran_matrix.c
  c_binding/cb_tr/pcompose_tran_matrix3.c
  c_binding/cb_tr/peval_view_map_matrix.c
  c_binding/cb_tr/peval_view_map_matrix3.c
  c_binding/cb_tr/peval_view_ori_matrix.c
  c_binding/cb_tr/peval_view_ori_matrix3.c
  c_binding/cb_tr/protate.c
  c_binding/cb_tr/protate_x.c
  c_binding/cb_tr/protate_y.c
  c_binding/cb_tr/protate_z.c
  c_binding/cb_tr/pscale.c
  c_binding/cb_tr/pscale3.c
  c_binding/cb_tr/ptran_point.c
  c_binding/cb_tr/ptran_point3.c
  c_binding/cb_tr/ptranslate.c
  c_binding/cb_tr/ptranslate3.c
  c_binding/cb_ws/pclose_ws.c
  c_binding/cb_ws/pinq_colr_rep.c
  c_binding/cb_ws/pinq_edge_rep.c
  c_binding/cb_ws/pinq_int_rep.c
  c_binding/cb_ws/pinq_invis_filter.c
  c_binding/cb_ws/pinq_line_rep.c
  c_binding/cb_ws/pinq_list_colr_inds.c
  c_binding/cb_ws/pinq_list_edge_inds.c
  c_binding/cb_ws/pinq_list_int_inds.c
  c_binding/cb_ws/pinq_list_line_inds.c
  c_binding/cb_ws/pinq_list_marker_inds.c
  c_binding/cb_ws/pinq_list_text_inds.c
  c_binding/cb_ws/pinq_list_view_inds.c
  c_binding/cb_ws/pinq_marker_rep.c
  c_binding/cb_ws/pinq_open_wss.c
  c_binding/cb_ws/pinq_text_rep.c
  c_binding/cb_ws/pinq_ws_conn_type.c
  c_binding/cb_ws/pinq_ws_st.c
  c_binding/cb_ws/pmessage.c
  c_binding/cb_ws/popen_ws.c
  c_binding/cb_ws/ppost_struct.c
  c_binding/cb_ws/predraw_all_structs.c
  c_binding/cb_ws/pset_colr_model.c
  c_binding/cb_ws/pset_colr_rep.c
  c_binding/cb_ws/pset_disp_upd_st.c
  c_binding/cb_ws/pset_edge_rep.c
  c_binding/cb_ws/pset_hlhsr_mode.c
  c_binding/cb_ws/pset_int_rep.c
  c_binding/cb_ws/pset_invis_filter.c
  c_binding/cb_ws/pset_light_src_rep.c
  c_binding/cb_ws/pset_line_rep.c
  c_binding/cb_ws/pset_marker_rep.c
  c_binding/cb_ws/pset_text_rep.c
  c_binding/cb_ws/pset_view_tran_in_pri.c
  c_binding/cb_ws/pset_ws_vp.c
  c_binding/cb_ws/pset_ws_vp3.c
  c_binding/cb_ws/pset_ws_win.c
  c_binding/cb_ws/pset_ws_win3.c
  c_binding/cb_ws/punpost_all_structs.c
  c_binding/cb_ws/punpost_struct.c
  c_binding/cb_ws/pupd_ws.c
  c_binding/cb_wst/pinq_disp_space_size3.c
  c_binding/cb_wst/pinq_ws_cat.c
  c_binding/helpers/build_tran_matrix.c
  c_binding/helpers/build_transform.c
  c_binding/helpers/build_transform3.c
  c_binding/helpers/check_event_class.c
  c_binding/helpers/check_loc_data_record.c
  c_binding/helpers/check_pick_data_record.c
  c_binding/helpers/check_stroke_data_record.c
  c_binding/helpers/inp_dispatch_next.c
  c_binding/helpers/inp_event_poll.c
  c_binding/helpers/input_ws_open.c
  c_binding/helpers/inq_filter.c
  c_binding/helpers/pinq_table_indices.c
  c_binding/helpers/request_device.c
  c_binding/helpers/sample_device.c
  c_binding/helpers/set_mode.c
  c_binding/helpers/valid_ar_fname.c
)

SET(P_F_BINDING_SRCS
  
  
  f_binding/fb_conf/pxndef.c
  f_binding/fb_conf/pxqhcsf.c
  f_binding/fb_conf/pxshcsf.c
  f_binding/fb_el/pads.c
  f_binding/fb_el/pexst.c
  f_binding/fb_el/pfa.c
  f_binding/fb_el/plb.c
  f_binding/fb_el/ppl.c
  f_binding/fb_el/ppl3.c
  f_binding/fb_el/ppm.c
  f_binding/fb_el/psatcu.c
  f_binding/fb_el/pschh.c
  f_binding/fb_el/pschsp.c
  f_binding/fb_el/pschup.c
  f_binding/fb_el/pschxp.c
  f_binding/fb_el/psedci.c
  f_binding/fb_el/psedfg.c
  f_binding/fb_el/psedi.c
  f_binding/fb_el/psedt.c
  f_binding/fb_el/psewsc.c
  f_binding/fb_el/psgmt3.c
  f_binding/fb_el/pshrid.c
  f_binding/fb_el/pshrm.c
  f_binding/fb_el/psiasf.c
  f_binding/fb_el/psici.c
  f_binding/fb_el/psis.c
  f_binding/fb_el/psln.c
  f_binding/fb_el/pslwsc.c
  f_binding/fb_el/psmk.c
  f_binding/fb_el/psmksc.c
  f_binding/fb_el/pspcli.c
  f_binding/fb_el/pspkid.c
  f_binding/fb_el/pspmci.c
  f_binding/fb_el/pspmi.c
  f_binding/fb_el/psvwi.c
  f_binding/fb_extel/pbsi.c
  f_binding/fb_extel/pfas3d.c
  f_binding/fb_extel/pres.c
  f_binding/fb_extel/psalch.c
  f_binding/fb_extel/psbic.c
  f_binding/fb_extel/psbici.c
  f_binding/fb_extel/psbis.c
  f_binding/fb_extel/psbisi.c
  f_binding/fb_extel/psbism.c
  f_binding/fb_extel/psbrfm.c
  f_binding/fb_extel/psfcm.c
  f_binding/fb_extel/psfdm.c
  f_binding/fb_extel/psii.c
  f_binding/fb_extel/psisi.c
  f_binding/fb_extel/psism.c
  f_binding/fb_extel/pslss.c
  f_binding/fb_extel/psmcli.c
  f_binding/fb_extel/psmcv3.c
  f_binding/fb_extel/psrfeq.c
  f_binding/fb_extel/psrfm.c
  f_binding/fb_extel/psrfp.c
  f_binding/fb_inp/pflush.c
  f_binding/fb_inp/pgtch.c
  f_binding/fb_inp/pgtpk.c
  f_binding/fb_inp/pgtvl.c
  f_binding/fb_inp/pinch3.c
  f_binding/fb_inp/pinlc.c
  f_binding/fb_inp/pinlc3.c
  f_binding/fb_inp/pinpk.c
  f_binding/fb_inp/pinst.c
  f_binding/fb_inp/pinst3.c
  f_binding/fb_inp/pinvl3.c
  f_binding/fb_inp/pprec.c
  f_binding/fb_inp/pqdlc3.c
  f_binding/fb_inp/prqch.c
  f_binding/fb_inp/prqlc3.c
  f_binding/fb_inp/prqpk.c
  f_binding/fb_inp/prqst.c
  f_binding/fb_inp/prqvl.c
  f_binding/fb_inp/pschm.c
  f_binding/fb_inp/pshlft.c
  f_binding/fb_inp/pslcm.c
  f_binding/fb_inp/psmlc.c
  f_binding/fb_inp/psmlc3.c
  f_binding/fb_inp/psmpk.c
  f_binding/fb_inp/psmst.c
  f_binding/fb_inp/pspkft.c
  f_binding/fb_inp/pspkm.c
  f_binding/fb_inp/psstm.c
  f_binding/fb_inp/psvlm.c
  f_binding/fb_inp/pwait.c
  f_binding/fb_pgse/pxshlc.c
  f_binding/fb_phg/pclph.c
  f_binding/fb_phg/popph.c
  f_binding/fb_str/dumpstr.c
  f_binding/fb_str/pcelst.c
  f_binding/fb_str/pclst.c
  f_binding/fb_str/pdas.c
  f_binding/fb_str/pdel.c
  f_binding/fb_str/pdst.c
  f_binding/fb_str/pels.c
  f_binding/fb_str/popst.c
  f_binding/fb_str/posep.c
  f_binding/fb_str/pqeco.c
  f_binding/fb_str/pqedm.c
  f_binding/fb_str/pqstrs.c
  f_binding/fb_str/pqstst.c
  f_binding/fb_str/psedm.c
  f_binding/fb_str/psep.c
  f_binding/fb_str/pseplb.c
  f_binding/fb_text/patr.c
  f_binding/fb_text/patr3.c
  f_binding/fb_text/psatal.c
  f_binding/fb_text/psatch.c
  f_binding/fb_text/psatp.c
  f_binding/fb_text/pstxal.c
  f_binding/fb_text/pstxci.c
  f_binding/fb_text/pstxfn.c
  f_binding/fb_text/pstxi.c
  f_binding/fb_text/pstxp.c
  f_binding/fb_text/pstxpr.c
  f_binding/fb_text/ptx.c
  f_binding/fb_text/ptx3.c
  f_binding/fb_tr/pbltm3.c
  f_binding/fb_tr/pevmm3.c
  f_binding/fb_tr/pevom3.c
  f_binding/fb_tr/pslmt3.c
  f_binding/fb_ws/pclwk.c
  f_binding/fb_ws/pmsg.c
  f_binding/fb_ws/popwk.c
  f_binding/fb_ws/ppost.c
  f_binding/fb_ws/pqcf.c
  f_binding/fb_ws/pqcr.c
  f_binding/fb_ws/pqhrm.c
  f_binding/fb_ws/pqpost.c
  f_binding/fb_ws/pqvwr.c
  f_binding/fb_ws/pqwkpo.c
  f_binding/fb_ws/pqwkt.c
  f_binding/fb_ws/pqwkt3.c
  f_binding/fb_ws/prst.c
  f_binding/fb_ws/pscm.c
  f_binding/fb_ws/pscr.c
  f_binding/fb_ws/psdus.c
  f_binding/fb_ws/psedr.c
  f_binding/fb_ws/psfname.c
  f_binding/fb_ws/psir.c
  f_binding/fb_ws/pslsr.c
  f_binding/fb_ws/psplr.c
  f_binding/fb_ws/pspmr.c
  f_binding/fb_ws/pstxr.c
  f_binding/fb_ws/psvwr3.c
  f_binding/fb_ws/pswkv3.c
  f_binding/fb_ws/pswkw.c
  f_binding/fb_ws/pswkw3.c
  f_binding/fb_ws/pupast.c
  f_binding/fb_ws/pupost.c
  f_binding/fb_ws/puwk.c
  f_binding/fb_ws/pxscm.c
  f_binding/fb_wst/pqdsp3.c
)
